//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Code.Meli.Api.WebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeHistory
    {
        public long Id { get; set; }
        public string Code { get; set; }
        public string Ip { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
    }
}
